### ISSUE TITLE
example broken, errors in log

### ISSUE THREAD

**Issue by ethernian** [UniversalLogin/UniversalLoginSDK#187]
Current build seems to be broken.

# 1. Errors in `dev:start` log
``` 
human@AllDev:~/work/UniversalLoginSDK/universal-login-example$ yarn dev:start
yarn run v1.12.3
$ babel-node scripts/dev-start.js
Starting ganache...
Ganache up and running on http://localhost:18545...
Deploying ENS contracts...
Deploying token contract...
Token contract address: 0x850437540FE07d02045f88cAe122Bc66B1BdE957
Starting relayer...
Deploying clicker contract...
Unhandled rejection Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)

(node:11509) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)
(node:11509) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
(node:11509) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
...
```
# 2. dropdown box never finishes loading

![image](https://user-images.githubusercontent.com/4574735/50793174-a22a8c00-12c7-11e9-89a3-180e27447b00.png)

# 3.  `./scripts/test.sh` fails 

```
4) Relayer - Config routes
       "before all" hook:
     Error: connect ECONNREFUSED 127.0.0.1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)

  5) Relayer - Config routes
       "after all" hook:
     TypeError: Cannot read property 'stop' of undefined
      at _callee3$ (test/relayer/routes/config.js:26:13)
      at tryCatch (/home/human/work/EthUniLog/UniversalLoginSDK/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (/home/human/work/EthUniLog/UniversalLoginSDK/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (/home/human/work/EthUniLog/UniversalLoginSDK/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114:21)
      at step (/home/human/work/EthUniLog/UniversalLoginSDK/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at /home/human/work/EthUniLog/UniversalLoginSDK/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
      at new Promise (<anonymous>)
      at new F (/home/human/work/EthUniLog/UniversalLoginSDK/node_modules/core-js/library/modules/_export.js:36:28)
      at Context.<anonymous> (/home/human/work/EthUniLog/UniversalLoginSDK/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)

  6) Relayer - Identity routes
       "before all" hook:
     Error: connect ECONNREFUSED 127.0.0.1:5432
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)

  7) Relayer - Identity routes
       "after all" hook:
     TypeError: Cannot read property 'stop' of undefined
      at _callee6$ (test/relayer/routes/relayer.js:74:13)
      at tryCatch (/home/human/work/EthUniLog/UniversalLoginSDK/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (/home/human/work/EthUniLog/UniversalLoginSDK/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (/home/human/work/EthUniLog/UniversalLoginSDK/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114:21)
      at step (/home/human/work/EthUniLog/UniversalLoginSDK/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at /home/human/work/EthUniLog/UniversalLoginSDK/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
      at new Promise (<anonymous>)
      at new F (/home/human/work/EthUniLog/UniversalLoginSDK/node_modules/core-js/library/modules/_export.js:36:28)
      at Context.<anonymous> (/home/human/work/EthUniLog/UniversalLoginSDK/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)

```

**Comment by JustynaBroniszewska** [comment]
Hi, thank you for your comment 😄 

We added a database to the relayer and we didn’t mention it in the README. Your tests failed, because they could not connect to a local database. To get it working you can try and install PostgreSQL locally or wait for us to update the README with more recent info.

**Comment by ethernian** [comment]
I have installed postgreSQL, but tests are still failing because of some missing configuraion (passwords?).
Should I try to fix the bugs on my own, or wait for updated README? When would you update it?

**Comment by JustynaBroniszewska** [comment]
We've already updated it. Please, tell us if it works for you now. 😉

**Comment by Kyrrui** [comment]
I was able to run the example with the latest guide & postgreSQL

**Comment by marekkirejczyk** [comment]
We updated `dev:start` script, it will now create the database automatically. So all you need to have is Postgres up and running. 

Closing for now. Feel free to reopen if still doesn't work
