### ISSUE TITLE
Relayer broken after commit de865de8b119de0a2808cfff64ee84c49d0445a6

### ISSUE THREAD

**Issue by gjeanmart** [UniversalLogin/UniversalLoginSDK#413]
**Issue:**
Cannot start the relayer after the [commit #de865de8b119de0a2808cfff64ee84c49d0445a6](https://github.com/UniversalLogin/UniversalLoginSDK/commit/de865de8b119de0a2808cfff64ee84c49d0445a6)

The relayer was working fine before this commit but now it throws the following exception:
```
$ yarn relayer:start
yarn run v1.15.2
$ node build/startRelayer.js
/home/gjeanmart/workspace/ethereum/universal-login/tutorial/app/UniversalLoginSDK/node_modules/ethers/errors.js:82
    throw error;
    ^

Error: cannot convert null value to array (arg="value", value=undefined, version=4.0.15)
    at Object.throwError (/home/gjeanmart/workspace/ethereum/universal-login/tutorial/app/UniversalLoginSDK/node_modules/ethers/errors.js:76:17)
    at Object.arrayify (/home/gjeanmart/workspace/ethereum/universal-login/tutorial/app/UniversalLoginSDK/node_modules/ethers/utils/bytes.js:45:16)
    at new SigningKey (/home/gjeanmart/workspace/ethereum/universal-login/tutorial/app/UniversalLoginSDK/node_modules/ethers/utils/signing-key.js:35:39)
    at new Wallet (/home/gjeanmart/workspace/ethereum/universal-login/tutorial/app/UniversalLoginSDK/node_modules/ethers/wallet.js:44:62)
    at new Relayer (/home/gjeanmart/workspace/ethereum/universal-login/tutorial/app/UniversalLoginSDK/universal-login-relayer/build/relayer.js:67:23)
    at Object.<anonymous> (/home/gjeanmart/workspace/ethereum/universal-login/tutorial/app/UniversalLoginSDK/universal-login-relayer/build/startRelayer.js:9:15)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Steps to reproduce**

1. clone the repository
```git clone git@github.com:UniversalLogin/UniversalLoginSDK.git ```

2. navigate to the folder `universal-login-relayer`

3. create the `.env` file
```
JSON_RPC_URL=https://ropsten.infura.io/v3/xxxxxxxxxxxxxxxxxx
PRIVATE_KEY=xxxxxxxxxxxxxxxxxx
ENS_DOMAIN_NAME=universal-login-tutorial.test
ENS_ADDRESS=0x112234455C3a32FD11230C42E7Bccd4A84e02010
PUBLIC_RESOLVER_ADDRESS=0x4C641FB9BAd9b60EF180c31F56051cE826d21A9A
 ```

4. Run the relayer
```
$ yarn relayer:start
```

**Expected behaviour**

Should start the relayer correctly!

**Fix**
In _UniversalLoginSDK / universal-login-relayer / lib / config / relayer.ts_. The relayer config needs to exported. At the end, add:
```
module.exports = config
```

**Comment by marekkirejczyk** [comment]
Should be fixed by #415

**Comment by gjeanmart** [comment]
Awesome! Thank you @marekkirejczyk 
I know it's still an early project, but you guys should consider separating stable code (`master` branch) from work in progress  (`dev` branch). 
In the same context, I noticed that the NPM package [universal-login-sdk](https://www.npmjs.com/package/universal-login-sdk) is two months old and not compatible anymore with the current version of the relayer in master.

**Comment by marekkirejczyk** [comment]
@gjeanmart 
New versions of npm released, now under `universal-login` organization:
https://www.npmjs.com/org/universal-login
(see updated docs).
We plan to release regularly starting from the end of April. 

At this point, it would be hard to distinguish between stable and unstable version.
We rather release often, automate as much testing as possible and fix quickly.

**Comment by gjeanmart** [comment]
That's really cool @marekkirejczyk 
I'm still learning and testing Universal-Login, so that npm packages will definitely help!
